services:
  orca:
    build: .
    container_name: resekon-orca-1
    ports:
      - "8000:8000"
    volumes:
      - type: volume
        source: orca_data
        target: /var/lib/jma-receipt
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/14/main
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /run:/run
      - /run/lock:/run/lock
      - /etc/machine-id:/etc/machine-id:ro
      - type: bind
        source: ./logs
        target: /var/log/jma-receipt
    tmpfs:
      - /tmp:exec,size=1G
    privileged: true
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    restart: unless-stopped
    environment:
      - TZ=Asia/Tokyo
      - LANG=ja_JP.UTF-8
      - LC_ALL=ja_JP.UTF-8
      - container=docker
      - POSTGRES_MAX_CONNECTIONS=100
      - POSTGRES_SHARED_BUFFERS=512MB
      - POSTGRES_WORK_MEM=16MB
      - POSTGRES_MAINTENANCE_WORK_MEM=128MB
      - POSTGRES_EFFECTIVE_CACHE_SIZE=1GB
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "7"
        compress: "true"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD-SHELL", "systemctl is-system-running --wait || exit 1"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 60s
    stop_grace_period: 2m
    stop_signal: SIGRTMIN+3
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      nproc:
        soft: 65536
        hard: 65536

volumes:
  orca_data:
    driver: local
  postgres_data:
    driver: local
